F07 frontend
cmurphy-cegep/projet-integrateur-deiber-ionut-romain pull request #42
Opened 2024-08-15 23:48 UTC by ionut8891

2024-08-16 00:02 UTC, eigarom requested changes

2024-08-16 00:02 UTC, eigarom commented on frontend/src/pages/catalogue/CommentairesRecette.vue
Il faudrait ajouter l'heure dans le commentaire :)

2024-08-19 13:16 UTC, ionut8891 commented on frontend/src/pages/catalogue/CommentairesRecette.vue
Done

2024-08-19 15:19 UTC, eigarom approved these changes

2024-08-19 15:19 UTC, merged